version: '3.1'

services:

  api:
    container_name: 'my-aspnetcore-app-prod'
    image: 'my-aspnetcore-app-prod'
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment: 
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
     - "80:80"
    depends_on:
     - "postgres"
    networks:
      - my-aspnetcore-network

  postgres:
    container_name: 'postgres-my-aspnetcore-app-prod'
    image: postgres:9.6.3
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - my-aspnetcore-network

networks:
  my-aspnetcore-network:
    driver: bridge

volumes:
  postgres: {}